# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "memeball"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "Mason"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

answers:
    honey-badger.gif: Honey badger doesn't care
    me_gusta.png: Me Gusta
    sweet_jesus.png: Sweet Jesus have mercy
    fuuuuuu.jpg: fuuuuuuuu
    Wat.jpg: wat
    oh_god_why.jpg: Oh God, why?
    challenge_accepted.png: Challenge accepted
    fuck_yea.png: Fuck yea
    aa-yeah.jpg: AAAAAAAWWWW YYYYEEEEAAAAA
    not_bad.jpg: Not bad
    seriously.jpg: Are you serious?
    y_u_no.jpg: Y U NO?
    me_gusta_mucho.png: Me Gusta Mucho
    do_a_barrel_roll.gif: Do a barrel roll!
    look_of_disapproval.jpg: Look of disapproval
    derp.jpg: Derp
    Courage_Wolf_01_by_Alma_de_Gato.jpg: What doesn't kill you, dies horribly
    

